### ISSUE TITLE
RDS Tag issue

### ISSUE THREAD

**Issue by zleswomp** [puppetlabs/puppetlabs-aws#413]
@daveseff Since the recent change in RDS tags in 9acca754bbf5abb20992568fa00f7773ceb3f74f I'm getting an error.  Would you be able to provide a fix for this?

```
Error: Failed to apply catalog: undefined method `db_instance_arn' for #<Aws::RDS::Types::DBInstance:0x00000005a8c190>
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:48:in `db_instance_to_hash'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:21:in `block (3 levels) in instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:19:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:19:in `block (2 levels) in instances'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/pageable_response.rb:75:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:18:in `block in instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:16:in `collect'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:16:in `instances'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/rds_instance/v2.rb:36:in `prefetch'
```

**Comment by daveseff** [comment]
@zleswomp You need to check your aws-sdk-core gem version.  Version 2.6 introduced the db_instance_arn parameter to rds_describe_instances response structure that the make rds tags feature in the puppet module possible.

**Comment by zleswomp** [comment]
@daveseff Thank you for the information.  I am indeed behind the times.
